CRUD_MVC_TDD/Models/CategoriaEstabelecimento.cs
namespace CRUD_MVC_TDD.Models
{
    public class CategoriaEstabelecimento
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

CRUD_MVC_TDD/Models/Estabelecimento.cs
using System.ComponentModel.DataAnnotations;

namespace CRUD_MVC_TDD.Models
{
    public class Estabelecimento
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public string CNPJ { get; set; }
        public string Email { get; set; }
        [DisplayFormat(DataFormatString = "{0:(99) 9999-9999}")]
        public string Telefone { get; set; }
        public int CategoriaId { get; set; }
        public bool Status { get; set; }

        public CategoriaEstabelecimento CategoriaEstabelecimento { get; set; }
    }
}

CRUD_MVC_TDD/Controllers/EstabelecimentoController.cs
using CRUD_MVC_TDD.Models;
using CRUD_MVC_TDD.Servicos;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System;

namespace CRUD_MVC_TDD.Controllers
{
    public class EstabelecimentoController : Controller
    {
        private readonly EstabelecimentoServico estabelecimentoServico;
        private readonly CategoriaEstabelecimentoServico categoriasServico;

        public EstabelecimentoController()
        {
            estabelecimentoServico = new EstabelecimentoServico();
            categoriasServico = new CategoriaEstabelecimentoServico();
        }

        public void CarregarCategorias()
        {
            ViewBag.Categorias = categoriasServico.ListarCategorias().Select(n => new SelectListItem()
            {
                Value = n.Id.ToString(),
                Text = n.Nome
            });
        }

        public ActionResult Index()
        {
            IEnumerable<Estabelecimento> estabelecimentos = estabelecimentoServico.ListarGrid();
            return View(estabelecimentos);
        }

        public ActionResult Inserir()
        {
            CarregarCategorias();
            return View();
        }

        public ActionResult Alterar(int id)
        {
            Estabelecimento estabelecimento = estabelecimentoServico.ObterPorId(id);
            CarregarCategorias();
            return View("~/Views/Estabelecimento/Inserir.cshtml", estabelecimento);
        }

        [HttpPost]
        public ActionResult Salvar(Estabelecimento estabelecimento)
        {
            List<string> resultado = new List<string>();

            if (estabelecimento.Id == 0)
            {
                resultado = estabelecimentoServico.Inserir(estabelecimento);
            }
            else
            {
                resultado = estabelecimentoServico.Alterar(estabelecimento);
            }

            if (!resultado.Any())
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["errosValidacoes"] = string.Join("<br>", resultado);
            }

            CarregarCategorias();
            return View("~/Views/Estabelecimento/Inserir.cshtml", estabelecimento);
        }

        public ActionResult Remover(int id)
        {
            estabelecimentoServico.Remover(estabelecimentoServico.ObterPorId(id));
            return RedirectToAction("Index");
        }
    }
}

CRUD_MVC_TDD/Views/Estabelecimento/Index.cshtml
@model IEnumerable<CRUD_MVC_TDD.Models.Estabelecimento>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}

<h2>Cadastro de Estabelecimentos</h2>

<p>
    <input class="btn btn-success" value="Inserir Estabelecimento" type="button" onclick="location.href='@Url.Action("Inserir", "Estabelecimento")';return false;" />
</p>
<div id="DivEstabelecimentos">
    <table class="table" id="tblEstabelecimentos" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NomeFantasia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CNPJ)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefone)
                </th>
                <th>
                    @Html.DisplayName("Categoria")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeFantasia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CNPJ)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriaEstabelecimento.Nome)
                </td>
                <td>
                    @(item.Status ? "Ativo" : "Inativo")
                </td>
                <td>
                    @Html.ActionLink("Editar", "Alterar", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Remover", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

<script src="~/Scripts/dataTables/js/jquery.dataTables.js"></script>
<script>
    //$(function () {
    $(document).ready(function ($) {
        $('#tblEstabelecimentos').dataTable({
            "language": {
                "loadingRecords": "Carregando...",
                "sProcessing": "processando...",
                "sZeroRecords": "sem registros",
                "sInfo": "Mostrando _START_ a _END_ de _TOTAL_",
                "sInfoEmpty": "0 até 0 de 0 registros",
                "sInfoFiltered": "(localizados de _MAX_  registros)",
                "sInfoPostFix": "",
                "sSearch": "Pesquisar:",
                "sUrl": "",
                "oPaginate": {
                    "First": "<<",
                    "sPrevious": "<",
                    "sNext": ">",
                    "sLast": ">>"
                }
            },
            "bLengthChange": false,
            "pageLength": 10
        });
    });
</script>

CRUD_MVC_TDD/Views/Estabelecimento/Inserir.cshtml
@model CRUD_MVC_TDD.Models.Estabelecimento
@{
    ViewBag.Title = "Inserir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (TempData["errosValidacoes"] != null)
    {
        <h3 style="color: red">@TempData["errosValidacoes"]</h3>
    }
}

@using (Html.BeginForm("Salvar", "Estabelecimento", FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>Estabelecimento</h4>
        <hr />
        @(Html.HiddenFor(m => m.Id))
        <div class="form-group">
            @Html.Label("Razão Social", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", maxlength = "30" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeFantasia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.NomeFantasia, new { htmlAttributes = new { @class = "form-control ", maxlength = "30" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Categoria" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(m => m.CategoriaId, ViewData["Categorias"] as IEnumerable<SelectListItem>, "Selecione", new { @class = "chosen-select form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", maxlength = "30" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ativo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.CheckBoxFor(m => m.Status, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script>
    $(document).ready(function ($) {
        $("#Telefone").mask("(99) 9999-9999");
        $("#CNPJ").mask("99.999.999/9999-99");
    });
</script>

CRUD_MVC_TDD/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;
<!DOCTYPE html>
<html>
<head>
    <title>
        @ViewBag.Title
    </title>
    @RenderSection("head", required: false)
    @Styles.Render("~/Content/bootstrap/Css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="@Url.Content("~/Scripts/jquery-2.2.4.js")" type="text/javascript"></script>*@
    <script src="~/Scripts/jquery.maskedinput.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>